server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sky_take_out?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 923923
  data:
    redis:
      # 这里的占位符名字必须改变，避免跟当前路径重名引发死循环
      host: ${sky.redis.config.host}
      port: ${sky.redis.config.port}
      password: ${sky.redis.config.password}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.sky.mapper: debug
    com.sky.service: info
    com.sky.controller: info

sky:
  jwt:
    admin-secret-key: itcast
    admin-ttl: 72000000
    admin-token-name: token

# Knife4j 接口文档配置
knife4j:
  enable: false

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
